import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import { getGlobalData } from "@/data/loader";
// import 'ionicons/css/ionicons.min.css';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
  weight: "100 900",
});

const poppinsBold = localFont({
  src: "./fonts/Poppins-SemiBold.ttf",
  variable: "--font-poppins-bold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Template",
  description: "Generated by create next app",
};

export async function generateGlobalData() {
  
  const globalData = await getGlobalData();
  if(!globalData) {
    console.error("Cannot get global data from backend! ")
    return null;
  }
  return globalData.data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const data = await generateGlobalData();

  const { header, footer } = data;

  return (
    <html lang="pl">
      <body
        className={`${poppinsRegular.variable} ${poppinsBold.variable} antialiased`}
      >
        <Header data={header}/>
        {children}
        <Footer data={footer}/>
      </body>
    </html>
  );
}
